services:
  hugo:
    image: hugomods/hugo:exts-0.123.8
    command: hugo server --bind 0.0.0.0
    environment:
      - HUGO_CACHEDIR=/opt/build/cache/hugo_cache/
    volumes:
      - ".:/src"
      - \\wsl.localhost\Ubuntu\usr\hugo_cache:/opt/build/cache/hugo_cache/
    ports:
      - "1313:1313"