name: Publish to Marketplace

on:
  workflow_run:
    workflows: ["Build Cornifer"]
    types:
      - completed

jobs:
  publish:
    name: Publish to Marketplace
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: cornifer-vsix

      - name: Publish to Marketplace
        uses: lannonbr/vsce-action@4.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.MARKETPLACE_PAT }}